package gateway_test

import (
	"testing"

	"github.com/KoukeNeko/JingClaw/core/internal/gateway"
)

// The thing being counted: a model asked for Markdown tables that drew one
// out of bars and dashes inside a fence anyway.
func TestADrawnTableInAFenceIsNoticed(t *testing.T) {
	answer := "報告：\n\n```text\n" +
		"+------+------+\n" +
		"| 類別 | 譯名 |\n" +
		"+------+------+\n" +
		"| 學園 | 赤冬 |\n" +
		"+------+------+\n" +
		"```\n"

	if !gateway.DrawsATableInAFence(answer) {
		t.Error("a drawn table was not noticed")
	}
}

// Everything that must not be counted, because counting it would eventually
// become an argument for rewriting it — and rewriting any of these turns
// bytes somebody believes are verbatim into something that only looks like
// them.
func TestOutputIsNotMistakenForADrawnTable(t *testing.T) {
	for name, answer := range map[string]string{
		"no fence at all": "| a | b |\n|---|---|\n| 1 | 2 |\n",

		"a command's output": "```\n$ go test ./...\n" +
			"ok  \tpackage/one\t0.3s\nFAIL\tpackage/two\t1.1s\n```\n",

		"a diff": "```diff\n--- a/main.go\n+++ b/main.go\n" +
			"@@ -1,3 +1,3 @@\n-old\n+new\n```\n",

		"a table with prose in the fence": "```\n" +
			"+---+---+\n| a | b |\n+---+---+\n" +
			"note: generated by the report tool\n```\n",

		"two rows only": "```\n| a | b |\n| 1 | 2 |\n```\n",

		"empty": "",
	} {
		if gateway.DrawsATableInAFence(answer) {
			t.Errorf("%s was counted as a drawn table", name)
		}
	}
}

// A MySQL client writes exactly this, and so does a model drawing a table.
// Nothing in the text separates them, which is why this counts rather than
// repairs: being wrong the other way would rewrite somebody's output.
func TestTheAmbiguousCaseIsCountedAndNothingMore(t *testing.T) {
	answer := "```\n+----+--------+\n| id | name   |\n+----+--------+\n" +
		"|  1 | 王小明 |\n+----+--------+\n```\n"

	// Counted, because it looks like one.
	if !gateway.DrawsATableInAFence(answer) {
		t.Error("the ambiguous case was not counted")
	}

	// And the only thing that happened is that it was counted: there is no
	// call here that changes the text, and there must never be one.
	if got := answer; got != "```\n+----+--------+\n| id | name   |\n+----+--------+\n"+
		"|  1 | 王小明 |\n+----+--------+\n```\n" {
		t.Errorf("the answer was altered: %q", got)
	}
}
