package viewfixture_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	"github.com/KoukeNeko/JingClaw/core/internal/runtime/viewfixture"
)

// The reference agrees with the cases it is the reference for.
//
// Circular only in appearance: the cases are written by hand from what a
// reader should see, and the reducer from what the events mean. When the two
// disagree, one of them is wrong and the disagreement is the point.
func TestTheReferenceAgreesWithEveryCase(t *testing.T) {
	for _, testCase := range viewfixture.Cases() {
		t.Run(testCase.Name, func(t *testing.T) {
			got := viewfixture.ReduceAll(testCase.Events)

			if !reflect.DeepEqual(got, testCase.Expected) {
				gotJSON, _ := json.MarshalIndent(got, "", "  ")
				wantJSON, _ := json.MarshalIndent(testCase.Expected, "", "  ")
				t.Errorf("%s\n\ngot:\n%s\n\nwant:\n%s",
					testCase.Why, gotJSON, wantJSON)
			}
		})
	}
}

// Every case says what it is for. A fixture whose purpose nobody remembers is
// one somebody eventually deletes as redundant.
func TestEveryCaseExplainsItself(t *testing.T) {
	for _, testCase := range viewfixture.Cases() {
		if testCase.Name == "" {
			t.Error("a case has no name, so a failure names an index")
		}
		if len(testCase.Why) < 40 {
			t.Errorf("%q does not say what a client gets wrong without it", testCase.Name)
		}
		if len(testCase.Events) == 0 {
			t.Errorf("%q applies no events", testCase.Name)
		}
	}
}

// The cases are written where the other clients can read them.
//
// A fixture that only Go can load is one only Go is checked against, which is
// the situation this exists to end.
func TestTheCasesAreWrittenOutForEverybody(t *testing.T) {
	path := filepath.Join("..", "..", "..", "..", "fixtures", "session-view.json")

	encoded, err := json.MarshalIndent(map[string]any{
		"comment": "Every client must produce these states from these events. " +
			"Generated by internal/runtime/viewfixture; edit the cases there.",
		"cases": viewfixture.Cases(),
	}, "", "  ")
	if err != nil {
		t.Fatalf("encode: %v", err)
	}
	encoded = append(encoded, '\n')

	existing, err := os.ReadFile(path)
	if err == nil && string(existing) == string(encoded) {
		return
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("create directory: %v", err)
	}
	if err := os.WriteFile(path, encoded, 0o644); err != nil {
		t.Fatalf("write: %v", err)
	}
	if existing != nil {
		t.Errorf("%s was out of date and has been rewritten; commit it", path)
	}
}
